import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
   return (
      <div className="h-screen">
         <Head>
            <title>Destiny Item Watch</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/images/favicon/favicon.ico" />
         </Head>

         <main className="flex h-screen w-full items-center justify-center">
            <h1 className="text-xl">Welcome to Destiny Item Watch</h1>
         </main>
      </div>
   )
}

export default Home
